// Package headers contains common headers used internally.
package header

const (
	Accept              = "Accept"
	AcceptEncoding      = "Accept-Encoding"
	ContentType         = "Content-Type"
	ContentEncoding     = "Content-Encoding"
	Allow               = "Allow"
	Authorization       = "Authorization"
	ContentDisposition  = "Content-Disposition"
	Vary                = "Vary"
	Origin              = "Origin"
	ContentLength       = "Content-length"
	Connection          = "Connection"
	Trailer             = "Trailer"
	Location            = "Location"
	CacheControl        = "Cache-Control"
	Cookie              = "Cookie"
	SetCookie           = "Set-Cookie"
	IfModifiedSince     = "If-Modified-Since"
	LastModified        = "Last-Modified"
	RetryAfter          = "Retry-After"
	Upgrade             = "Upgrade"
	WWWAuthenticate     = "WWW-Authenticate"
	XForwardedFor       = "X-Forwarded-For"
	XForwardedProto     = "X-Forwarded-Proto"
	XForwardedProtocol  = "X-Forwarded-Protocol"
	XForwardedSsl       = "X-Forwarded-Ssl"
	XUrlScheme          = "X-Url-Scheme"
	XHTTPMethodOverride = "X-HTTP-Method-Override"
	XRealIP             = "X-Real-Ip"
	XRequestID          = "X-Request-Id"
	XCorrelationID      = "X-Correlation-Id"
	XRequestedWith      = "X-Requested-With"
	Server              = "Server"

	AccessControlRequestMethod    = "Access-Control-Request-Method"
	AccessControlAllowOrigin      = "Access-Control-Allow-Origin"
	AccessControlAllowMethods     = "Access-Control-Allow-Methods"
	AccessControlAllowHeaders     = "Access-Control-Allow-Header"
	AccessControlExposeHeaders    = "Access-Control-Expose-Header"
	AccessControlMaxAge           = "Access-Control-max-Age"
	AccessControlAllowCredentials = "Access-Control-Allow-Credentials"
	AccessControlRequestHeaders   = "Access-Control-Request-Header"

	StrictTransportSecurity         = "Strict-Transport-Security"
	XContentTypeOptions             = "X-Content-Type-Options"
	XXSSProtection                  = "X-XSS-Protection"
	XFrameOptions                   = "X-Frame-Options"
	ContentSecurityPolicy           = "Content-Security-Policy"
	ContentSecurityPolicyReportOnly = "Content-Security-Policy-Report-Only"
	XCSRFToken                      = "X-CSRF-Token"
	ReferrerPolicy                  = "Referrer-Policy"
)
