// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: mgrpc/internal/protobuf/test.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HiReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HiReq) Reset() {
	*x = HiReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrpc_internal_protobuf_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiReq) ProtoMessage() {}

func (x *HiReq) ProtoReflect() protoreflect.Message {
	mi := &file_mgrpc_internal_protobuf_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiReq.ProtoReflect.Descriptor instead.
func (*HiReq) Descriptor() ([]byte, []int) {
	return file_mgrpc_internal_protobuf_test_proto_rawDescGZIP(), []int{0}
}

func (x *HiReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HiRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HiRes) Reset() {
	*x = HiRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrpc_internal_protobuf_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiRes) ProtoMessage() {}

func (x *HiRes) ProtoReflect() protoreflect.Message {
	mi := &file_mgrpc_internal_protobuf_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiRes.ProtoReflect.Descriptor instead.
func (*HiRes) Descriptor() ([]byte, []int) {
	return file_mgrpc_internal_protobuf_test_proto_rawDescGZIP(), []int{1}
}

func (x *HiRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrpc_internal_protobuf_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_mgrpc_internal_protobuf_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_mgrpc_internal_protobuf_test_proto_rawDescGZIP(), []int{2}
}

func (x *ListReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrpc_internal_protobuf_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_mgrpc_internal_protobuf_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_mgrpc_internal_protobuf_test_proto_rawDescGZIP(), []int{3}
}

func (x *ListItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_mgrpc_internal_protobuf_test_proto protoreflect.FileDescriptor

var file_mgrpc_internal_protobuf_test_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x21,
	0x0a, 0x05, 0x48, 0x69, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x21, 0x0a, 0x05, 0x48, 0x69, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x23, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x32, 0x71, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x48,
	0x69, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x48, 0x69, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x30, 0x01, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x61,
	0x6c, 0x67, 0x61, 0x64, 0x6f, 0x2f, 0x6d, 0x6f, 0x63, 0x68, 0x61, 0x2f, 0x76, 0x33, 0x2f, 0x6d,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mgrpc_internal_protobuf_test_proto_rawDescOnce sync.Once
	file_mgrpc_internal_protobuf_test_proto_rawDescData = file_mgrpc_internal_protobuf_test_proto_rawDesc
)

func file_mgrpc_internal_protobuf_test_proto_rawDescGZIP() []byte {
	file_mgrpc_internal_protobuf_test_proto_rawDescOnce.Do(func() {
		file_mgrpc_internal_protobuf_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_mgrpc_internal_protobuf_test_proto_rawDescData)
	})
	return file_mgrpc_internal_protobuf_test_proto_rawDescData
}

var file_mgrpc_internal_protobuf_test_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mgrpc_internal_protobuf_test_proto_goTypes = []interface{}{
	(*HiReq)(nil),    // 0: protobuf.HiReq
	(*HiRes)(nil),    // 1: protobuf.HiRes
	(*ListReq)(nil),  // 2: protobuf.ListReq
	(*ListItem)(nil), // 3: protobuf.ListItem
}
var file_mgrpc_internal_protobuf_test_proto_depIdxs = []int32{
	0, // 0: protobuf.TestService.Greetings:input_type -> protobuf.HiReq
	2, // 1: protobuf.TestService.List:input_type -> protobuf.ListReq
	1, // 2: protobuf.TestService.Greetings:output_type -> protobuf.HiRes
	3, // 3: protobuf.TestService.List:output_type -> protobuf.ListItem
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mgrpc_internal_protobuf_test_proto_init() }
func file_mgrpc_internal_protobuf_test_proto_init() {
	if File_mgrpc_internal_protobuf_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mgrpc_internal_protobuf_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrpc_internal_protobuf_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrpc_internal_protobuf_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrpc_internal_protobuf_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mgrpc_internal_protobuf_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mgrpc_internal_protobuf_test_proto_goTypes,
		DependencyIndexes: file_mgrpc_internal_protobuf_test_proto_depIdxs,
		MessageInfos:      file_mgrpc_internal_protobuf_test_proto_msgTypes,
	}.Build()
	File_mgrpc_internal_protobuf_test_proto = out.File
	file_mgrpc_internal_protobuf_test_proto_rawDesc = nil
	file_mgrpc_internal_protobuf_test_proto_goTypes = nil
	file_mgrpc_internal_protobuf_test_proto_depIdxs = nil
}
