.ONESHELL:
.DEFAULT_GOAL := help

.PHONY: help
help: ## show help
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

run-basic: ## run basic example
	@go run basic/main.go
